// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Showces - Professional Screen Recording",
  description:
    "Record your screen like never before. Showces brings professional screen recording to your fingertips. Capture, edit, and share with unprecedented ease.",
  openGraph: {
    title: "Showces - Professional Screen Recording",
    description:
      "Record your screen like never before. Capture, edit, and share with unprecedented ease.",
    url: "https://showces.vercel.app", // Update with your actual domain
    siteName: "Showces",
    images: [
      {
        url: "/launch.png",
        width: 1200,
        height: 630,
        alt: "Showces Screen Recording App",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Showces - Professional Screen Recording",
    description:
      "Record your screen like never before. Capture, edit, and share with unprecedented ease.",
    images: ["/launch.png"],
  },
  icons: {
    icon: "/icon.png",
  },
  metadataBase: new URL("https://showces.vercel.app"), // Update with your actual domain
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
